variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase

##################################################################################
# setups
##################################################################################

.cvmfs: &cvmfs
  image: atlasadc/atlas-grid-centos7
  tags:
    - cvmfs
  
.atlasroot: &atlasroot
  <<: *cvmfs  
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "python default" && lsetup cmake; set -e
    - set +e && lsetup "root recommended"; set -e    
    - export CXX=$(which g++)
    - export CC=$(which gcc)
    - bash scripts/getpip.sh
    
.hcombroot: &hcombroot
  <<: *cvmfs  
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "python default" && lsetup cmake; set -e
    - set +e && lsetup "root 6.04.16-HiggsComb-x86_64-slc6-gcc49-opt"; set -e
    - export CXX=$(which g++)
    - export CC=$(which gcc)
    - bash scripts/getpip.sh
    
.latestroot: &latestroot
  image:
    name: rootproject/root:latest
    entrypoint: [""]
  before_script:
    - apt-get update
    - apt-get install -y python
    - bash scripts/getpip.sh
    
.atlstats: &atlstats
  image: 
    name: atlasamglab/stats-base:latest
    entrypoint: [""]
  before_script:
    - bash scripts/getpip.sh    
  
.analysisbase: &analysisbase
  image: atlas/analysisbase:21.2.120
  before_script:
    - source /home/atlas/release_setup.sh
    - bash scripts/getpip.sh


##################################################################################
# stages
##################################################################################

stages:
  - build
  - run

.build: &build
  stage: build
  artifacts:
    expire_in: 1d
    paths:
      - build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    
.run: &run
  stage: run
  script:
    - cd build
    - source setup.sh
    - ctest --output-on-failure
  artifacts:
    expire_in: 1d
    paths:
      - "*.pdf"      
      - "*.tex"
      - "*.json"


##################################################################################
# jobs
##################################################################################

# build

latestroot_build:
  <<: *latestroot
  <<: *build

atlasroot_build:
  <<: *atlasroot
  <<: *build  

hcombroot_build:
  <<: *hcombroot
  <<: *build

  script:
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake .. 
    - make
  
analysisbase_build:
  <<: *analysisbase
  <<: *build

atlstats_build:
  <<: *atlstats
  <<: *build

# run  

atlasroot_run:
  <<: *atlasroot
  <<: *run
  dependencies:
    - atlasroot_build

latestroot_run:
  <<: *latestroot
  <<: *run
  dependencies:
    - latestroot_build

hcombroot_run:
  <<: *hcombroot
  <<: *run
  dependencies:
    - hcombroot_build
  
analysisbase_run:
  <<: *analysisbase
  <<: *run
  dependencies:
    - analysisbase_build
  
atlstats_run:
  <<: *atlstats
  <<: *run
  dependencies:
    - atlstats_build
