variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase

##################################################################################
# setups
##################################################################################

.cvmfs: &cvmfs
  image: atlasadc/atlas-grid-centos7
  tags:
    - cvmfs

.latex: &latex
  image: gitlab-registry.cern.ch/cburgard/latex:latest

.atlasroot: &atlasroot
  <<: *cvmfs
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "python pilot-default" && set -e
    - set +e && lsetup cmake; set -e
    - set +e && lsetup "root recommended"; set -e
    - export CMAKE_PREFIX_PATH=$JSONMCPP__HOME:$VDT__HOME:$CMAKE_PREFIX_PATH
    - export CXX=$(which g++)
    - export CC=$(which gcc)

.hcombroot: &hcombroot
  <<: *cvmfs
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "python pilot-default" && set -e
    - set +e && lsetup cmake; set -e
    - set +e && lsetup "root 6.04.16-HiggsComb-x86_64-slc6-gcc49-opt"; set -e
    - export CXX=$(which g++)
    - export CC=$(which gcc)

.latestroot: &latestroot
  image:
    name: rootproject/root:latest
    entrypoint: [""]
  before_script:
    - apt-get update
    - apt-get install -y python-is-python3

.atlstats: &atlstats
  image:
    name: atlasamglab/stats-base:latest
    entrypoint: [""]

.analysisbase: &analysisbase
  <<: *cvmfs
  image: gitlab-registry.cern.ch/atlas/athena/analysisbase:21.2.270
  before_script:
    - source /home/atlas/release_setup.sh
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "python pilot-default" && set -e

##################################################################################
# stages
##################################################################################

stages:
  - build
  - run
  - render

.build: &build
  stage: build
  artifacts:
    expire_in: 1d
    paths:
      - build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

.run: &run
  stage: run
  script:
    - cd build
    - source setup.sh
    - bash ../scripts/getpip.sh
    - ctest --output-on-failure
  artifacts:
    expire_in: 3mo
    paths:
      - "*.root"
      - "*.txt"
      - "*.tex"
      - "*.json"

.render: &render
  stage: render
  script:
    - for file in *.tex; do pdflatex $file; done
  artifacts:
    expire_in: 3mo
    paths:
      - "*.pdf"

##################################################################################
# jobs
##################################################################################

# build

latestroot_build:
  <<: *latestroot
  <<: *build

atlasroot_build:
  <<: *atlasroot
  <<: *build

hcombroot_build:
  <<: *hcombroot
  <<: *build
  script:
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake ..
    - make

analysisbase_build:
  <<: *analysisbase
  <<: *build

atlstats_build:
  <<: *atlstats
  <<: *build

# run

atlasroot_run:
  <<: *atlasroot
  <<: *run
  dependencies:
    - atlasroot_build

latestroot_run:
  <<: *latestroot
  <<: *run
  dependencies:
    - latestroot_build

hcombroot_run:
  <<: *hcombroot
  <<: *run
  dependencies:
    - hcombroot_build

analysisbase_run:
  <<: *analysisbase
  <<: *run
  dependencies:
    - analysisbase_build

atlstats_run:
  <<: *atlstats
  <<: *run
  dependencies:
    - atlstats_build

# render

atlasroot_render:
  <<: *latex
  <<: *render
  dependencies:
    - atlasroot_run

latestroot_render:
  <<: *latex
  <<: *render
  dependencies:
    - latestroot_run

hcombroot_render:
  <<: *latex
  <<: *render
  dependencies:
    - hcombroot_run

analysisbase_render:
  <<: *latex
  <<: *render
  dependencies:
    - analysisbase_run

atlstats_render:
  <<: *latex
  <<: *render
  dependencies:
    - atlstats_run
