variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase

image: atlas/analysisbase:21.2.49

stages:
  - build

cmake_standalone_compile:
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
  tags:
    - cvmfs

  image: gitlab-registry.cern.ch/atlas-caf/cafcore:caflibs
    
  stage: build

  artifacts:
    expire_in: 1d
    untracked: true
    paths:
    - build
    - setup.sh
  
  script:
    - set +e && lsetup "root 6.14.04-x86_64-slc6-gcc62-opt"; lsetup cmake; set -e
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake ..
    - make

cmake_hcomb_compile:
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
  tags:
    - cvmfs

  image: gitlab-registry.cern.ch/atlas-caf/cafcore:caflibs
    
  stage: build

  artifacts:
    expire_in: 1d
    untracked: true
    paths:
    - build
    - setup.sh
  
  script:
    - set +e && lsetup "root 6.04.16-HiggsComb-x86_64-slc6-gcc49-opt"; set -e
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake .. 
    - make

  
cmake_asg_compile:
  stage: build

  artifacts:
    expire_in: 1d
    untracked: true
    paths:
    - build

  script:
    - source /home/atlas/release_setup.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
