variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase

##################################################################################
# setups
##################################################################################

.latestroot_base: &latestroot_base
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "root recommended"; lsetup cmake; set -e
  tags:
    - cvmfs

  image: gitlab-registry.cern.ch/atlas-caf/cafcore:caflibs
    
.hcombroot_base: &hcombroot_base
  before_script:
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - set +e && lsetup "root 6.04.16-HiggsComb-x86_64-slc6-gcc49-opt"; set -e
  tags:
    - cvmfs

  image: gitlab-registry.cern.ch/atlas-caf/cafcore:caflibs

.asg_base: &asg_base
  before_script:
    - source /home/atlas/release_setup.sh

  image: atlas/analysisbase:21.2.49

##################################################################################
# stages
##################################################################################

stages:
  - build
  - run

.build_base: &build_base
  stage: build
  artifacts:
    expire_in: 1d
    paths:
    - build

.run_base: &run_base
  stage: run
  
  script:
    - source build/setup.sh
    - ./scripts/fit.py --input test/workspace.root --workspace Test --data asimovData --hesse --scan mu 10 0 2  --output mytest.txt 


##################################################################################
# jobs
##################################################################################

latestroot_compile:
  <<: *latestroot_base
  <<: *build_base
  
  script:
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake ..
    - make

hcombroot_compile:
  <<: *hcombroot_base
  <<: *build_base

  script:
    - export CXX=$(which g++)
    - mkdir build
    - cd build
    - cmake -DCMAKE_MODULE_PATH=$ROOTSYS/etc/cmake .. 
    - make

  
asg_compile:
  <<: *asg_base
  <<: *build_base

  script:
    - mkdir build
    - cd build
    - cmake ..
    - make


latestroot_run:
  <<: *latestroot_base
  <<: *run_base
  dependencies:
    - latestroot_compile

hcombroot_run:
  <<: *hcombroot_base
  <<: *run_base
  dependencies:
    - hcombroot_compile
  
asg_run:
  <<: *asg_base
  <<: *run_base
  dependencies:
    - asg_compile


